title: LumenPath HMS
description: Hospital Management System — multi‑org deployment
url: "https://shazej.github.io"
baseurl: "" # user site must keep this empty
permalink: pretty
markdown: kramdown
kramdown:
input: GFM